import React, { useState } from "react";
import { useReportHistory, useDownloadDecisionPdf, useDownloadDecisionExcel } from "../hooks/useReports";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  FileText, 
  FileSpreadsheet, 
  Clock, 
  User, 
  Download, 
  Loader2,
  ChevronLeft,
  ChevronRight,
  FolderArchive
} from "lucide-react";
import { ReportItem } from "../types/reports";

export function ReportHistoryArchive() {
  const [page, setPage] = useState(0);
  const pageSize = 10;
  const { data: reportsData, isLoading } = useReportHistory(page, pageSize);

  const downloadPdf = useDownloadDecisionPdf();
  const downloadExcel = useDownloadDecisionExcel();
  const [activeReportId, setActiveReportId] = useState<number | null>(null);

  const handleReDownload = (item: ReportItem) => {
    if (!item.decisionId) return;
    setActiveReportId(item.reportId);
    if (item.reportType === "PDF") {
      downloadPdf.mutate(
        { decisionId: item.decisionId, title: item.decisionTitle },
        { onSettled: () => setActiveReportId(null) }
      );
    } else {
      downloadExcel.mutate(
        { decisionId: item.decisionId, title: item.decisionTitle },
        { onSettled: () => setActiveReportId(null) }
      );
    }
  };

  const reports = reportsData?.content || [];
  const totalPages = reportsData?.totalPages || 0;

  if (isLoading) {
    return (
      <div className="py-16 text-center text-slate-500 bg-white rounded-xl border border-[#E2E8F0]">
        <Loader2 className="w-8 h-8 animate-spin mx-auto mb-3 text-purple-600" />
        <p>Loading report generation logs...</p>
      </div>
    );
  }

  if (reports.length === 0) {
    return (
      <div className="py-16 text-center text-slate-500 bg-white rounded-xl border border-[#E2E8F0]">
        <FolderArchive className="w-12 h-12 mx-auto mb-3 text-slate-300" />
        <h3 className="text-lg font-semibold text-[#0F172A]">No Generated Reports Yet</h3>
        <p className="text-sm text-slate-400 mt-1">
          Export a decision or community report above to start building your archive.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl border border-[#E2E8F0] shadow-sm overflow-hidden space-y-0">
      <div className="p-4 border-b border-[#E2E8F0] bg-slate-50/50 flex justify-between items-center">
        <div>
          <h3 className="font-semibold text-slate-900">Audit Trail & Generated Reports</h3>
          <p className="text-xs text-slate-500">Record of reports compiled and exported by administrators</p>
        </div>
        <Badge variant="secondary" className="font-semibold">
          {reportsData?.totalElements || reports.length} Total Logs
        </Badge>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-50 border-b border-[#E2E8F0] text-slate-600 font-semibold">
            <tr>
              <th className="py-3.5 px-4">Report Target</th>
              <th className="py-3.5 px-4">Format</th>
              <th className="py-3.5 px-4">Generated By</th>
              <th className="py-3.5 px-4">Timestamp</th>
              <th className="py-3.5 px-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E2E8F0]">
            {reports.map((rep) => {
              const isDownloading =
                (downloadPdf.isPending || downloadExcel.isPending) && activeReportId === rep.reportId;

              return (
                <tr key={rep.reportId} className="hover:bg-slate-50/80 transition-colors">
                  <td className="py-4 px-4 font-medium text-[#0F172A]">
                    <div>
                      <span className="font-semibold text-slate-900">
                        {rep.decisionTitle || `Decision Report #${rep.decisionId || rep.reportId}`}
                      </span>
                      {rep.communityName && (
                        <p className="text-xs text-slate-500 mt-0.5">{rep.communityName}</p>
                      )}
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <Badge
                      variant="outline"
                      className={
                        rep.reportType === "PDF"
                          ? "bg-red-50 text-red-700 border-red-200"
                          : "bg-emerald-50 text-emerald-700 border-emerald-200"
                      }
                    >
                      {rep.reportType === "PDF" ? (
                        <FileText className="w-3 h-3 mr-1" />
                      ) : (
                        <FileSpreadsheet className="w-3 h-3 mr-1" />
                      )}
                      {rep.reportType}
                    </Badge>
                  </td>
                  <td className="py-4 px-4 text-slate-600 text-xs">
                    <div className="flex items-center gap-1.5">
                      <User className="w-3.5 h-3.5 text-slate-400" />
                      <span>{rep.generatedBy?.fullName || rep.generatedBy?.username || "Admin"}</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 text-slate-500 text-xs">
                    <div className="flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-slate-400" />
                      {new Date(rep.generatedAt).toLocaleString()}
                    </div>
                  </td>
                  <td className="py-4 px-4 text-right">
                    {rep.decisionId ? (
                      <Button
                        size="sm"
                        variant="ghost"
                        className="text-purple-600 hover:text-purple-700 hover:bg-purple-50 h-8 text-xs font-semibold"
                        onClick={() => handleReDownload(rep)}
                        disabled={isDownloading}
                      >
                        {isDownloading ? (
                          <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" />
                        ) : (
                          <Download className="w-3.5 h-3.5 mr-1" />
                        )}
                        Download Again
                      </Button>
                    ) : (
                      <span className="text-slate-400 text-xs">Archived</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between p-4 border-t border-[#E2E8F0] bg-slate-50/50">
          <span className="text-xs text-slate-500">
            Page {page + 1} of {totalPages}
          </span>
          <div className="flex gap-1">
            <Button
              size="sm"
              variant="outline"
              disabled={page === 0}
              onClick={() => setPage((p) => Math.max(0, p - 1))}
              className="h-8 px-2"
            >
              <ChevronLeft className="w-4 h-4" />
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled={page >= totalPages - 1}
              onClick={() => setPage((p) => p + 1)}
              className="h-8 px-2"
            >
              <ChevronRight className="w-4 h-4" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
